language: en

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LexicalSyntacticFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "word"
- name: "DIETClassifier"
- name: "RegexEntityExtractor"
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: "SpacyNLP"
  model: "en_core_web_md"
- name: DIETClassifier
  epochs: 100
- name: RegexEntityExtractor
  use_lookup_tables: true
  use_regexes: True
  entity_recognition: True
  use_word_boundaries: True
- name: RegexEntityExtractor
- name: EntitySynonymMapper


policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
  core_fallback_action_name: "action_default_fallback"
  core_fallback_threshold: 0.3
- name: AugmentedMemoizationPolicy
assistant_id: 20240808-170718-best-sharp
