import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DarkModeProvider } from "@/context/DarkModeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <DarkModeProvider>{children}</DarkModeProvider>
      </body>
    </html>
  );
// export default async function LocaleLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <DarkModeProvider>
//       <html lang="en" className={inter.className}>
//         <body>{children}</body>
//       </html>
//     </DarkModeProvider>
//   );
}
