import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // return <>{children}</>;
  //himesh's edits for use case
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <div className="flex-1 flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
