AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  PlaygroundETL

  All ETL type task that have to take place to support Playground application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  PlaygroundETL:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      MemorySize: 1024
      PackageType: Image
      Policies: AmazonS3FullAccess
      Events:
        Test:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: rate(10 minutes)
            Input: '{ "name": "test" }'
        UpdateDaily:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "name": "update_daily" }'
        CollectedMonthly:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: rate(23 hours)
            Input: '{ "name": "collect_parkingsensor" }'
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: .
      Dockerfile: Dockerfile
