language: en

pipeline:
- name: "WhitespaceTokenizer"
#- name: "RegexFeaturizer"
- name: "LexicalSyntacticFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "word"
- name: "SpacyNLP"
  model: "en_core_web_md"
#- name: "rasa_plus.ml.LLMIntentClassifier"
#  embeddings:
#    type: "llamacpp"
#    model_path: "C:/Users/jubal/Documents/SIT374/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
- name: "custom_components.llm_interpreter.LlamaIntentClassifier"
#- name: "RegexEntityExtractor"
#  use_lookup_tables: true
#  use_regexes: true
#  entity_recognition: true
#  use_word_boundaries: true
#- name: EntitySynonymMapper
#  threshold: 0.4
#  ambiguity_threshold: 0.3

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
- name: AugmentedMemoizationPolicy
assistant_id: 20250401-183224-creamy-sync
