

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /applications/deakin/teamproject/MOP-Code/artificial-intelligence/Vehicle Classification/dataset # dataset root dir
train: images/train
val: images/val/
test: # test images (optional)

# Classes
names:
  0: Class1
  1: Class2
  2: Class3
  3: Class4
  4: Class5
  5: Class6
  6: Class7
  7: Class8
  8: Class9
  9: Class10
  10: Class11
  11: Class12
  12: Class13
 

