steps:
  # STEP 1 - CREATING STAGING ENVIRONMENT
  # Build the container image
  #- name: 'gcr.io/cloud-builders/docker'
  #args: ['build','-t','gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging','webapp/']
  # Push the container image to Container Registry
  #- #name: 'gcr.io/cloud-builders/docker'
  #args: ['push', 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging']
  # Deploy container image to Cloud Run
  #- #name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #entrypoint: gcloud
  #args:
  # - 'run'
  # - 'deploy'
  # - 'mop-code-webapp-staging'
  # - '--allow-unauthenticated'
  # - '--image'
  # - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging'
  # - '--region'
  # - 'australia-southeast1'

  #  STEP 2 - ACCEPTANCE TESTING ON STAGING ENVIRONMENT
  # Clone the repository
  #- name: 'gcr.io/cloud-builders/git'
  #  args: ['clone', 'https://github.com/Chameleon-company/MOP-Acceptance-Tests.git']
  #  # Build Container
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['build','-t','gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-acceptance-test','./MOP-Acceptance-Tests']
  #  # Push the container image to Container Registry
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['push', 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-acceptance-test']
  # Run Tests
  #- name: 'gcr.io/cloud-builders/docker'
  #  entrypoint: bash
  #  args:
  #   - '-c'
  #   - 'docker run gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-acceptance-test'

  # STEP 3 - CREATING PRODUCTION ENVIRONMENT
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp",
        "webapp/",
      ]
    # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mop-code-webapp"
      - "--allow-unauthenticated"
      - "--image"
      - "gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp"
      - "--region"
      - "australia-southeast1"
images:
  - "gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp"
# - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging'
# - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-acceptance-test'
timeout: 4000s
