options:
  logging: GCS_ONLY

steps:
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'australia-southeast1-docker.pkg.dev/sit-22t1-city-of-melbo-d86dc19/cloud-run-source-deploy/next-webapp:$COMMIT_SHA'
      - '.'
    dir: 'next_webapp'

  - id: 'Push to Artifact Registry'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'australia-southeast1-docker.pkg.dev/sit-22t1-city-of-melbo-d86dc19/cloud-run-source-deploy/next-webapp:$COMMIT_SHA'

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'next-webapp-staging'
      - '--image=australia-southeast1-docker.pkg.dev/sit-22t1-city-of-melbo-d86dc19/cloud-run-source-deploy/next-webapp:$COMMIT_SHA'
      - '--region=australia-southeast1'
      - '--platform=managed'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-secrets=MONGODB_URI=mongodb-uri:latest,JWT_SECRET=JWT_SECRET:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,SUPABASE_API_KEY=supabase-api-key:latest'
      - '--set-env-vars=SMTP_HOST=smtp.gmail.com,SMTP_PORT=587,SMTP_USER=mopchameleon@gmail.com,SMTP_FROM=mopchameleon@gmail.com,GCS_IMAGES_BUCKET=gs://mop-images,SUPABASE_URL=https://jusajjfvjxtlkafmscwx.supabase.co'

  - id: 'Allow Deakin Domain Access'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'next-webapp-staging'
      - '--region=australia-southeast1'
      - '--member=domain:deakin.edu.au'
      - '--role=roles/run.invoker'

images:
  - 'australia-southeast1-docker.pkg.dev/sit-22t1-city-of-melbo-d86dc19/cloud-run-source-deploy/next-webapp:$COMMIT_SHA'