apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs-container
        image: s223743838/next_webapp-web:latest  # or use DockerHub image if not building locally
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://s223743838:password-123@cluster0.gpmpazp.mongodb.net/MOP"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30082  # Kubernetes will expose this at <NodeIP>:30082
